### ISSUE TITLE
500 benign  prompts from LAION

### ISSUE THREAD

**Issue by KevinLight831** [Artanisax/Six-CD#1]
Did the author forget to release the subset with 500 benign prompts  from LAION for the out-of-prompt CLIP score？

**Comment by Artanisax** [comment]
Thanks for the reminder. We didn't release them since one can sample benign prompts from the original LAION dataset to achieve a similar result. Now we've put them under `Datasets` directory.

**Comment by KevinLight831** [comment]
Thank you for the reply.  However,  the column "evaluation_seed" of this benign prompt csv file is missing. is the same specific "evaluation_seed" used？

**Comment by Artanisax** [comment]
Yes, the same evaluation seeds are applied to all methods. And they are in the last  (third) column of the `.csv` file.
